apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  namespace: bigip-demo
  labels:
    app: agent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      serviceAccountName: ai-agent
      containers:
      - name: agent-service
        image: quay.io/trinathsquay/agent-service:latest
        ports:
        - containerPort: 5001
        env:
          - name: TARGET_SERVICE
            value: "ai-cluster-service"
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: bigip-demo
spec:
  type: NodePort
  selector:
    app: agent-service
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001