apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent
  namespace: bigip-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-agent-scaler
rules:
  # Permissions for scaling deployments.
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "update", "patch"]
  # Permissions to update the AS3 ConfigMap.
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update", "patch"]
  # Permissions to get services.
- apiGroups: [""]
  resources: ["services", "nodes", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-agent-scaler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ai-agent-scaler
subjects:
- kind: ServiceAccount
  name: ai-agent
  namespace: bigip-demo