apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      serviceAccountName: ai-agent
      containers:
      - name: agent-service
        image: agent-service:latest
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
        - name: training-storage
          mountPath: /app/training_data
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
      - name: training-storage
        persistentVolumeClaim:
          claimName: training-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
spec:
  type: NodePort
  selector:
    app: agent-service
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001