apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-retrain-cron
  namespace: bigip-demo
  labels:
    app: model-service
spec:
  schedule: "*/5 * * * *"  # Retrain every 5 minutes (adjust as needed)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: retrain-job
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - "curl -X POST http://model-service:5000/retrain"
          restartPolicy: OnFailure