apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
  namespace: bigip-demo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 26a56558-9eca-4421-9d1c-171488b8184e
  seLinuxOptions:
    user: "system_u"
    role: "system_r"
    type: "svirt_lxc_net_t"
    level: "s0"


--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: bigip-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual