apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: bigip-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-pvc
  namespace: bigip-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi