apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pvc
spec:
  capacity:
    storage: 10Gi  # This is the required storage field, specifying 5Gi of space.
  accessModes:
    - ReadWriteMany  # The volume can only be mounted by a single node as read-write.
  persistentVolumeReclaimPolicy: Retain  # What happens when the PVC is deleted (can be Retain, Recycle, or Delete)
  storageClassName: manual  # If you're using a storage class, specify it here. If not, you can leave it out.
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 26a56558-9eca-4421-9d1c-171488b8184e  # Replace <node-name> with the actual name of the node where you want the volume to reside.
  hostPath:
    path: /tmp/data  # Path to the directory on the host node's filesystem.
    type: DirectoryOrCreate  # Optional: This ensures that the directory is created if it doesn't exist.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: bigip-demo  # Ensure it’s the same namespace as your deployment
spec:
  accessModes:
    - ReadWriteMany  # Allow multiple services to read/write to the volume
  resources:
    requests:
      storage: 10Gi  # Request the same size as the PV
  storageClassName: manual  # Must match the PV's storage class