apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model
  namespace: ai-workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-model
  template:
    metadata:
      labels:
        app: ai-model
    spec:
      containers:
        - name: ai-model
          image: quay.io/trinathsquay/waf-ai-model:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: shared-volume
              mountPath: /data  # Mount the shared PVC to /data directory inside the container
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: model-shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ai-model-service
  namespace: ai-workloads
spec:
  selector:
    app: ai-model
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000