apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-shared-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Allow multiple pods to read/write to this volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Match the PVC's storage class
  hostPath:
    path: /mnt/data  # The shared directory on the node
    type: Directory  # Ensure it's a directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-shared-pvc
  namespace: ai-workloads  # Ensure it’s the same namespace as your deployment
spec:
  accessModes:
    - ReadWriteMany  # Allow multiple services to read/write to the volume
  resources:
    requests:
      storage: 5Gi  # Request the same size as the PV
  storageClassName: manual  # Must match the PV's storage class