apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-shared-volume
  spec:
    capacity:
      storage: 5Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: manual
    nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - 26a56558-9eca-4421-9d1c-171488b8184e  # Replace with the node name where you want to mount the directory
    hostPath:
      path: /var/home/core/data  # Path on the host node's filesystem
      type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-shared-pvc
  namespace: ai-workloads  # Ensure it’s the same namespace as your deployment
spec:
  accessModes:
    - ReadWriteMany  # Allow multiple services to read/write to the volume
  resources:
    requests:
      storage: 5Gi  # Request the same size as the PV
  storageClassName: manual  # Must match the PV's storage class