apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  namespace: ai-workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
      - name: ai-agent
        image: quay.io/trinathsquay/ai-asm-anomaly-agent:latest
        ports:
        - containerPort: 5000
        env:
        - name: KUBECONFIG # Environment variable name
          value: "/root/.kube/kubeconfig" # Path inside the container
        volumeMounts:
          - name: kubeconfig-volume
            mountPath: "/root/.kube"
            subPath: "kubeconfig"
            readOnly: true # Important: Mount as read-only
      imagePullSecrets:
        - name: myquay
      volumes:
      - name: kubeconfig-volume
          secret:
            secretName: ai-agent-kubeconfig
---

apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  namespace: ai-workloads
spec:
  type: NodePort
  selector:
    app: ai-agent
  ports:
    - protocol: TCP
      port: 5000        # AI Agent container port
      targetPort: 5000  # AI Agent application port
      nodePort: 30001   # Exposed NodePort
