apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ai-workloads
  name: ai-agent-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ai-workloads
  name: ai-agent-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: ai-workloads
roleRef:
  kind: Role
  name: ai-agent-role
  apiGroup: rbac.authorization.k8s.io